package com.dashapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SprintAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintAllPropertiesEquals(Sprint expected, Sprint actual) {
        assertSprintAutoGeneratedPropertiesEquals(expected, actual);
        assertSprintAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintAllUpdatablePropertiesEquals(Sprint expected, Sprint actual) {
        assertSprintUpdatableFieldsEquals(expected, actual);
        assertSprintUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintAutoGeneratedPropertiesEquals(Sprint expected, Sprint actual) {
        assertThat(actual)
            .as("Verify Sprint auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintUpdatableFieldsEquals(Sprint expected, Sprint actual) {
        assertThat(actual)
            .as("Verify Sprint relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintUpdatableRelationshipsEquals(Sprint expected, Sprint actual) {
        assertThat(actual)
            .as("Verify Sprint relationships")
            .satisfies(a -> assertThat(a.getOwner()).as("check owner").isEqualTo(expected.getOwner()));
    }
}
